import type { Metadata } from "next";
import { Orbitron } from "next/font/google";
import "./globals.css";


const orbitronSans = Orbitron({
  variable: "--font-orbitron-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${orbitronSans.variable} ${orbitronSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
